APP_TITLE = "JuFo-Ki"
APP_WIDTH = 500
APP_HEIGHT = 500
INFO_WIDTH_CONTROL = 7
BAR_HEIGHT_CONTROL = 11

BUTTON_FG = "white"
BUTTON_BG="#4CAF50"
BUTTON_ACTIVEBACKGROUND="#45a049"

BAR_COLOR = "purple4"
IMAGE_FRAME_COLOR = "gray"
INFO_FRAME_COLOR = "green"